/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import SocialProfiles from "@/components/SocialProfiles";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"h-full "}>
        <div className="w-full fixed top-0  z-40">
          <Navbar />
        </div>
        <div className="fixed top-[150px] z-50 left-0 ml-10 flex flex-col justify-center items-center gap-2 max-sm:hidden">
          <SocialProfiles />
        </div>
        {children}

        <div className=" w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
